require('dotenv').config();
const express = require('express');
const session = require('express-session');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const db = require('./db/database');
const app = express();
const PORT = Number(process.env.PORT || 3000), HOST = process.env.HOST || '127.0.0.1';
app.use(express.urlencoded({extended:true})); app.use(express.json());
app.use(session({secret:process.env.SESSION_SECRET || 'local-demo-session-secret-change-me',resave:false,saveUninitialized:false,cookie:{sameSite:'lax'}}));
app.use('/static',express.static(path.join(__dirname,'../public')));
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const user=req=>req.session.user;
function layout(req,title,body){const u=user(req); return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | CyberLearn</title><link rel="stylesheet" href="/static/css/site.css"></head><body><header><a class="brand" href="/">Cyber<span>Learn</span></a><nav><a href="/courses">Courses</a><a href="/search">Explore</a><a href="/support">Support</a>${u?`<a href="/dashboard">My learning</a><a href="/cart">Cart</a>${u.role==='admin'?'<a href="/admin">Admin</a>':''}<form class="inline" method="post" action="/logout"><button>Sign out</button></form>`:`<a href="/login">Log in</a><a class="button" href="/register">Get started</a>`}</nav></header><main>${body}</main><footer>© 2026 CyberLearn · Local university demonstration · All names and records are fictional.</footer></body></html>`}
const requireUser=(req,res,next)=>user(req)?next():res.redirect('/login');
const requireAdmin=(req,res,next)=>user(req)?.role==='admin'?next():res.status(403).send(layout(req,'Access denied','<section class="panel"><h1>Access denied</h1><p>This area is for platform administrators.</p></section>'));
const courseCard=c=>`<article class="course-card"><div class="course-art">${esc(c.difficulty)}</div><div><small>${esc(c.category)}</small><h3><a href="/course/${c.id}">${esc(c.title)}</a></h3><p>${esc(c.instructor)} · ${esc(c.duration)}</p><div>★ ${c.rating} <strong>${money(c.price*(1-c.discount/100))}</strong>${c.discount?` <s>${money(c.price)}</s>`:''}</div></div></article>`;

app.get('/',(req,res)=>{const cs=db.prepare('SELECT courses.*,categories.name category FROM courses JOIN categories ON category_id=categories.id ORDER BY rating DESC LIMIT 6').all(); const cats=db.prepare('SELECT * FROM categories').all();res.send(layout(req,'Learn Cybersecurity',`<section class="hero"><div><p class="eyebrow">CAREER-READY CYBERSECURITY EDUCATION</p><h1>Learn Cybersecurity.<br><em>Build Real Skills.</em></h1><p>Practical courses designed by working security professionals. Study at your pace, build confidence, and grow your career.</p><a class="button" href="/courses">Browse courses</a></div><aside><b>12,000+</b><span>active learners</span><b>4.8/5</b><span>average course rating</span></aside></section><section><h2>Explore by topic</h2><div class="categories">${cats.map(c=>`<a href="/courses?category=${c.id}"><b>${esc(c.name)}</b><span>${esc(c.description)}</span></a>`).join('')}</div></section><section><div class="section-title"><h2>Popular courses</h2><a href="/courses">View all courses →</a></div><div class="grid">${cs.map(courseCard).join('')}</div></section>`));});
app.get('/courses',(req,res)=>{let sql='SELECT courses.*,categories.name category FROM courses JOIN categories ON category_id=categories.id', args=[]; if(req.query.category){sql+=' WHERE category_id=?';args=[req.query.category]} const cs=db.prepare(sql).all(...args);res.send(layout(req,'Courses',`<section class="page-head"><p class="eyebrow">CATALOGUE</p><h1>Courses built for real-world security work</h1><form class="search" action="/search"><input name="q" placeholder="Search courses, skills or instructors"><button>Search</button></form></section><div class="grid">${cs.map(courseCard).join('')}</div>`));});
app.get('/course/:id',(req,res)=>{const c=db.prepare('SELECT courses.*,categories.name category FROM courses JOIN categories ON category_id=categories.id WHERE courses.id=?').get(req.params.id);if(!c)return res.status(404).send('Course not found');const rs=db.prepare('SELECT reviews.*,users.name FROM reviews JOIN users ON users.id=reviews.user_id WHERE course_id=? ORDER BY reviews.id DESC').all(c.id);res.send(layout(req,c.title,`<section class="detail"><div><p class="eyebrow">${esc(c.category)}</p><h1>${esc(c.title)}</h1><p class="lead">${esc(c.description)}</p><p>Created by <b>${esc(c.instructor)}</b> · ★ ${c.rating} · ${c.students.toLocaleString()} learners</p><div class="lesson"><h3>What you'll learn</h3><p>${esc(c.content)}</p><p>${esc(c.duration)} · ${esc(c.difficulty)}</p></div><h2>Learner reviews</h2>${rs.map(r=>`<article class="review"><b>${esc(r.name)}</b> · ★ ${r.rating}<p>${r.comment}</p></article>`).join('')||'<p>No reviews yet.</p>'}</div><aside class="buy"><div class="course-art">${esc(c.difficulty)}</div><h2>${money(c.price*(1-c.discount/100))}</h2>${c.discount?`<p><s>${money(c.price)}</s> · ${c.discount}% off</p>`:''}<form method="post" action="/cart/add"><input type="hidden" name="course_id" value="${c.id}"><button class="button">Add to cart</button></form><p>Full lifetime access<br>Certificate of completion</p></aside></section><section class="panel"><h2>Leave a review</h2>${user(req)?`<form method="post" action="/reviews"><input type="hidden" name="course_id" value="${c.id}"><select name="rating"><option>5</option><option>4</option><option>3</option></select><textarea name="comment" required placeholder="Share your experience"></textarea><button>Submit review</button></form>`:'<p><a href="/login">Log in</a> to review this course.</p>'}</section>`));});
// INTENTIONALLY VULNERABLE FOR WEB SECURITY DEMONSTRATION: string concatenation enables local SQLite SQL injection.
// SECURE IMPLEMENTATION: db.prepare('SELECT ... WHERE title LIKE ? OR description LIKE ?').all(`%${q}%`, `%${q}%`)
app.get('/search',(req,res)=>{const q=req.query.q||'';let rows=[];try{rows=db.prepare(`SELECT courses.*,categories.name category FROM courses JOIN categories ON category_id=categories.id WHERE courses.title LIKE '%${q}%' OR courses.description LIKE '%${q}%'`).all()}catch(e){return res.status(500).send(layout(req,'Search error',`<section class="panel"><h1>Search unavailable</h1><pre>${esc(e.message)}</pre></section>`))}res.send(layout(req,'Search',`<section class="page-head"><h1>Search courses</h1><form class="search"><input name="q" value="${q}" placeholder="Search"><button>Search</button></form><p>Results for: <b>${q}</b></p></section><div class="grid">${rows.map(courseCard).join('')||'<p>No courses matched your search.</p>'}</div>`));});
app.get('/login',(req,res)=>res.send(layout(req,'Log in',`<section class="auth panel"><h1>Welcome back</h1><form method="post" action="/login"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="button">Log in</button></form><p>New to CyberLearn? <a href="/register">Create an account</a>.</p></section>`)));
// INTENTIONALLY VULNERABLE: local demo login deliberately has no rate limit/lockout and gives verbose errors.
// SECURE IMPLEMENTATION: apply account/IP rate limiting, generic errors, progressive delay, and bcrypt.compare.
app.post('/login',(req,res)=>{const r=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email);if(!r)return res.status(401).send(layout(req,'Login failed','<section class="auth panel"><h1>Login failed</h1><p>No account exists for that email address.</p><a href="/login">Try again</a></section>'));const tested=r.password_scheme==='sha256-unsalted'?crypto.createHash('sha256').update(req.body.password||'').digest('hex'):req.body.password; if(tested!==r.password_hash)return res.status(401).send(layout(req,'Login failed','<section class="auth panel"><h1>Login failed</h1><p>The password is incorrect for this account.</p><a href="/login">Try again</a></section>'));req.session.user={id:r.id,name:r.name,email:r.email,role:r.role};res.redirect('/dashboard')});
app.get('/register',(req,res)=>res.send(layout(req,'Create account',`<section class="auth panel"><h1>Create your account</h1><form method="post" action="/register"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="button">Create account</button></form></section>`)));
app.post('/register',(req,res)=>{try{const x=db.prepare('INSERT INTO users(name,email,password_hash,password_scheme,phone,address) VALUES(?,?,? ,"plaintext","","")').run(req.body.name,req.body.email,req.body.password);req.session.user={id:x.lastInsertRowid,name:req.body.name,email:req.body.email,role:'student'};res.redirect('/dashboard')}catch(e){res.status(400).send(layout(req,'Registration error',`<section class="panel"><h1>Could not create account</h1><p>${esc(e.message)}</p></section>`))}});
app.post('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/')));
app.get('/dashboard',requireUser,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(user(req).id);const orders=db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC').all(u.id);const learning=db.prepare('SELECT DISTINCT courses.* FROM order_items JOIN orders ON orders.id=order_items.order_id JOIN courses ON courses.id=order_items.course_id WHERE orders.user_id=?').all(u.id);res.send(layout(req,'My learning',`<section class="page-head"><p class="eyebrow">LEARNER DASHBOARD</p><h1>Welcome back, ${esc(u.name.split(' ')[0])}</h1><p>Continue learning and manage your CyberLearn account.</p></section><div class="stat-row"><div><b>${learning.length}</b><span>Courses</span></div><div><b>${orders.length}</b><span>Orders</span></div><div><b>${u.discountPercent}%</b><span>Member discount</span></div></div><section><h2>My courses</h2><div class="grid">${learning.map(courseCard).join('')||'<p>Your library is ready for its first course.</p>'}</div></section><section class="panel"><h2>Recent orders</h2>${orders.map(o=>`<p><a href="/order/${o.id}">Order #${o.id}</a> · ${money(o.total)} · ${esc(o.status)}</p>`).join('')||'<p>No orders yet.</p>'}<p><a href="/profile/${u.id}">Manage profile</a> · <a href="/support">Contact support</a></p></section>`));});
app.post('/cart/add',requireUser,(req,res)=>{const exists=db.prepare('SELECT id FROM cart_items WHERE user_id=? AND course_id=?').get(user(req).id,req.body.course_id);if(!exists)db.prepare('INSERT INTO cart_items(user_id,course_id) VALUES(?,?)').run(user(req).id,req.body.course_id);res.redirect('/cart')});
app.get('/cart',requireUser,(req,res)=>{const items=db.prepare('SELECT cart_items.*,courses.* FROM cart_items JOIN courses ON courses.id=cart_items.course_id WHERE user_id=?').all(user(req).id);const total=items.reduce((s,c)=>s+c.price*(1-c.discount/100),0);res.send(layout(req,'Shopping cart',`<section class="page-head"><h1>Your cart</h1><p>Review your courses before completing your simulated purchase.</p></section><section class="panel">${items.map(c=>`<div class="cart-line"><div><b>${esc(c.title)}</b><span>${esc(c.instructor)}</span></div><strong>${money(c.price*(1-c.discount/100))}</strong><form method="post" action="/cart/remove"><input type="hidden" name="course_id" value="${c.course_id}"><button>Remove</button></form></div>`).join('')||'<p>Your cart is empty.</p>'}</section>${items.length?`<section class="checkout-summary"><h2>Total: ${money(total)}</h2><a class="button" href="/checkout">Proceed to checkout</a></section>`:''}`));});
app.post('/cart/remove',requireUser,(req,res)=>{db.prepare('DELETE FROM cart_items WHERE user_id=? AND course_id=?').run(user(req).id,req.body.course_id);res.redirect('/cart')});
app.get('/checkout',requireUser,(req,res)=>{const items=db.prepare('SELECT cart_items.*,courses.* FROM cart_items JOIN courses ON courses.id=cart_items.course_id WHERE user_id=?').all(user(req).id);const total=items.reduce((s,c)=>s+c.price*(1-c.discount/100),0);res.send(layout(req,'Checkout',`<section class="auth panel"><p class="eyebrow">SIMULATED CHECKOUT</p><h1>Complete your order</h1><p>No payment information is collected. This is a local demonstration purchase.</p><form method="post" action="/checkout"><input type="hidden" name="total" value="${total}">${items.map(c=>`<input type="hidden" name="course_id" value="${c.course_id}"><input type="hidden" name="price" value="${c.price*(1-c.discount/100)}"><p>${esc(c.title)} <b>${money(c.price*(1-c.discount/100))}</b></p>`).join('')}<label>Billing address<input name="address" value="12 Fictional Learning Lane, Demo City"></label><button class="button">Place simulated order · ${money(total)}</button></form></section>`));});
// INTENTIONALLY VULNERABLE FOR WEB SECURITY DEMONSTRATION: authoritative prices/totals come from the client body.
// SECURE IMPLEMENTATION: for each course ID, query its current price and calculate discounts and total on the server.
app.post('/checkout',requireUser,(req,res)=>{let ids=[].concat(req.body.course_id||[]), prices=[].concat(req.body.price||[]);const orderId=Number(db.prepare('SELECT COALESCE(MAX(id),1000)+1 id FROM orders').get().id);const total=Number(req.body.total);db.prepare('INSERT INTO orders(id,user_id,total,status,payment_reference,shipping_address) VALUES(?,?,?,?,?,?)').run(orderId,user(req).id,total,'Paid',`DEMO-CHECKOUT-${orderId}`,req.body.address||'');ids.forEach((id,i)=>{const c=db.prepare('SELECT title FROM courses WHERE id=?').get(id);if(c)db.prepare('INSERT INTO order_items(order_id,course_id,title,price) VALUES(?,?,?,?)').run(orderId,id,c.title,Number(prices[i]||prices[0]||0))});db.prepare('DELETE FROM cart_items WHERE user_id=?').run(user(req).id);res.redirect('/order/'+orderId)});
// INTENTIONALLY VULNERABLE: checks that a local order exists but omits owner validation (IDOR).
// SECURE IMPLEMENTATION: reject unless o.user_id === req.session.user.id (or the session role is admin).
app.get('/order/:id',requireUser,(req,res)=>{const o=db.prepare('SELECT orders.*,users.name,users.email FROM orders JOIN users ON users.id=orders.user_id WHERE orders.id=?').get(req.params.id);if(!o)return res.status(404).send('Order not found');const items=db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id);res.send(layout(req,'Order '+o.id,`<section class="panel"><p class="eyebrow">ORDER CONFIRMATION</p><h1>Order #${o.id}</h1><p>Customer: <b>${esc(o.name)}</b> · ${esc(o.email)}</p><p>Status: <b>${esc(o.status)}</b> · ${money(o.total)}</p>${items.map(i=>`<div class="cart-line"><span>${esc(i.title)}</span><strong>${money(i.price)}</strong></div>`).join('')}<p>Billing address: ${esc(o.shipping_address)}</p><p>Reference: ${esc(o.payment_reference)}</p></section>`));});
// INTENTIONALLY VULNERABLE: profile object is fetched without an ownership check (IDOR).
// SECURE IMPLEMENTATION: allow only req.params.id === session user id, except for authorized administrators.
app.get('/profile/:id',requireUser,(req,res)=>{const p=db.prepare('SELECT id,name,email,phone,address,bio,role,discountPercent,courseAccess,email_preferences,created_at FROM users WHERE id=?').get(req.params.id);if(!p)return res.status(404).send('Profile not found');const mine=Number(p.id)===Number(user(req).id);res.send(layout(req,'Profile',`<section class="auth panel"><h1>${mine?'My profile':esc(p.name)+' profile'}</h1><p>Email: ${esc(p.email)} · Member since ${esc(p.created_at)}</p><form method="post" action="/api/profile"><label>Name<input name="name" value="${esc(p.name)}"></label><label>Bio<textarea name="bio">${esc(p.bio)}</textarea></label><label>Phone<input name="phone" value="${esc(p.phone)}"></label><label>Email preferences<select name="email_preferences"><option value="1">Subscribed</option><option value="0">Unsubscribed</option></select></label><button class="button">Save profile</button></form></section>`));});
// INTENTIONALLY VULNERABLE: mass assignment plus no CSRF validation for account-changing request.
// SECURE IMPLEMENTATION: update only an explicit name/bio/phone/preferences allowlist after CSRF/origin validation.
app.all('/api/profile',requireUser,(req,res)=>{const body=req.method==='GET'?req.query:req.body;const allowedInsecure=['name','bio','phone','role','isAdmin','discountPercent','courseAccess','email_preferences'];Object.keys(body).filter(k=>allowedInsecure.includes(k)).forEach(k=>db.prepare(`UPDATE users SET ${k}=? WHERE id=?`).run(body[k],user(req).id));const updated=db.prepare('SELECT * FROM users WHERE id=?').get(user(req).id);req.session.user.role=updated.role; if(req.accepts('html'))return res.redirect('/profile/'+user(req).id);res.json({ok:true,user:updated});});
app.post('/reviews',requireUser,(req,res)=>{db.prepare('INSERT INTO reviews(user_id,course_id,rating,comment) VALUES(?,?,?,?)').run(user(req).id,req.body.course_id,req.body.rating,req.body.comment);res.redirect('/course/'+req.body.course_id)});
app.get('/support',(req,res)=>res.send(layout(req,'Support',`<section class="auth panel"><h1>How can we help?</h1><p>Our learner support team normally responds within one business day.</p>${user(req)?`<form method="post" action="/support"><label>Subject<input name="subject" required></label><label>Message<textarea name="message" required></textarea></label><button class="button">Send message</button></form>`:'<p><a href="/login">Log in</a> to contact support.</p>'}</section>`)));
app.post('/support',requireUser,(req,res)=>{db.prepare('INSERT INTO support_messages(user_id,subject,message) VALUES(?,?,?)').run(user(req).id,req.body.subject,req.body.message);res.redirect('/support?sent=1')});
app.get('/admin',requireAdmin,(req,res)=>{const stats={users:db.prepare('SELECT COUNT(*) n FROM users').get().n,courses:db.prepare('SELECT COUNT(*) n FROM courses').get().n,orders:db.prepare('SELECT COUNT(*) n FROM orders').get().n,revenue:db.prepare("SELECT COALESCE(SUM(total),0) n FROM orders WHERE status='Paid'").get().n};const recent=db.prepare('SELECT orders.*,users.name FROM orders JOIN users ON users.id=orders.user_id ORDER BY orders.id DESC LIMIT 6').all();res.send(layout(req,'Admin dashboard',`<section class="page-head"><p class="eyebrow">PLATFORM ADMINISTRATION</p><h1>Business overview</h1></section><div class="stat-row"><div><b>${stats.users}</b><span>Users</span></div><div><b>${stats.courses}</b><span>Courses</span></div><div><b>${stats.orders}</b><span>Orders</span></div><div><b>${money(stats.revenue)}</b><span>Revenue</span></div></div><section class="admin-nav"><a href="/admin/users">User management</a><a href="/admin/courses">Course management</a><a href="/admin/orders">Order management</a><a href="/admin/database">Database information</a></section><section class="panel"><h2>Recent orders</h2>${recent.map(o=>`<p>#${o.id} · ${esc(o.name)} · ${money(o.total)} · ${esc(o.status)}</p>`).join('')}</section>`));});
app.get('/admin/users',requireAdmin,(req,res)=>{const rows=db.prepare('SELECT id,name,email,role,phone,discountPercent,created_at FROM users').all();res.send(layout(req,'Users',`<section class="page-head"><h1>User management</h1></section>${table(rows,['id','name','email','role','phone','discountPercent','created_at'])}`))});
app.get('/admin/courses',requireAdmin,(req,res)=>res.send(layout(req,'Course management',`<section class="page-head"><h1>Course management</h1></section>${table(db.prepare('SELECT id,title,instructor,price,discount,students FROM courses').all(),['id','title','instructor','price','discount','students'])}`)));
app.get('/admin/orders',requireAdmin,(req,res)=>res.send(layout(req,'Order management',`<section class="page-head"><h1>Order management</h1></section>${table(db.prepare('SELECT orders.*,users.name FROM orders JOIN users ON users.id=orders.user_id ORDER BY orders.id DESC').all(),['id','name','total','status','payment_reference','created_at'])}`)));
function table(rows,fields){return `<div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th>${esc(f)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${fields.map(f=>`<td>${esc(r[f])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
app.get('/admin/database',requireAdmin,(req,res)=>{const names=['users','courses','orders','order_items','reviews','support_messages','uploaded_files','audit_logs'];res.send(layout(req,'Database information',`<section class="page-head"><p class="eyebrow">DATABASE VIEWER</p><h1>CyberLearn local database</h1><p>Development-only overview of the application data store.</p></section>${names.map(n=>`<section class="panel"><h2>${n}</h2>${table(db.prepare(`SELECT * FROM ${n} LIMIT 20`).all(),db.prepare(`PRAGMA table_info(${n})`).all().map(x=>x.name))}</section>`).join('')}`))});
// INTENTIONALLY VULNERABLE: this JSON endpoint checks login only; hiding Admin UI is not authorization.
// SECURE IMPLEMENTATION: register requireAdmin before this handler, as the HTML admin routes do.
app.get('/api/admin/users',requireUser,(req,res)=>res.json(db.prepare('SELECT id,name,email,password_hash,password_scheme,phone,address,role,isAdmin,discountPercent,courseAccess FROM users').all()));
app.get('/api/admin/orders',requireUser,(req,res)=>res.json(db.prepare('SELECT * FROM orders ORDER BY id DESC').all()));
// Deliberately weak file selection: accepts a caller-provided name. Resolution is constrained to demo-data, never host files.
// SECURE IMPLEMENTATION: use a database file ID, map it to a known filename, normalize it, and enforce an allowlist.
app.get('/download',requireUser,(req,res)=>{const requested=String(req.query.file||'course-manual.pdf').replaceAll('..','');const root=path.resolve(__dirname,'../demo-data');const candidate=path.resolve(root,requested);if(!candidate.startsWith(root+path.sep) && candidate!==root)return res.status(400).send('Invalid demo document');if(!fs.existsSync(candidate)||!fs.statSync(candidate).isFile())return res.status(404).send('Demo document not found');res.download(candidate,path.basename(candidate));});
app.get('/resources',requireUser,(req,res)=>{const files=db.prepare('SELECT * FROM uploaded_files').all();res.send(layout(req,'Course resources',`<section class="page-head"><h1>Course resources</h1><p>Downloadable learning documents for this local demonstration.</p></section><section class="panel">${files.map(f=>`<p><a href="/download?file=${encodeURIComponent(f.stored_name)}">${esc(f.filename)}</a></p>`).join('')}</section>`));});
// INTENTIONALLY VERBOSE LOCAL DEBUG endpoint: only synthetic configuration and schema metadata are shown.
// SECURE IMPLEMENTATION: remove this route outside development and return generic operational errors.
app.get('/debug',(req,res)=>res.json({application:'CyberLearn',version:'1.0.0-local-demo',database:'SQLite',environment:process.env.NODE_ENV||'development',eventMode:process.env.EVENT_MODE,syntheticConfig:{mailHost:'mail.demo.invalid',apiKey:'fake-demo-key-not-real'},routes:['/courses','/search','/order/:id','/api/admin/users','/download','/api/reset'],tables:db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(x=>x.name)}));
app.post('/api/reset',(req,res)=>{if(process.env.EVENT_MODE!=='true')return res.status(403).json({error:'Reset is available only in local event mode'});db.close();fs.unlinkSync(path.resolve(process.cwd(),process.env.DATABASE_PATH||'./data/cyberlearn.db'));require('child_process').execFileSync(process.execPath,['scripts/seed.js'],{cwd:process.cwd()});res.json({ok:true,message:'Database reset. Restart the application to reopen the seeded database.'})});
app.use((req,res)=>res.status(404).send(layout(req,'Not found','<section class="panel"><h1>Page not found</h1><p>The page you requested does not exist.</p></section>')));
app.listen(PORT,HOST,()=>console.log(`CyberLearn running at http://${HOST}:${PORT}`));
